version: "3.8"
services:
    client:
        build:
            context: ./client
        ports:
            - "4200:80"
        container_name: client
        depends_on:
            [server1.1,server1.2,server1.3,server1.4,server1.5, server2.1,server2.3,server2.4,server2.6,server2.7,server2.8,server2.9,server2.10,server2.11,server2.12,server2.13,server2.14,server2.15,server2.16, server3.1,server3.2,server3.3,server3.4,server3.5,server3.6,server3.7,server3.8]

    server1.1:
        build:
            context: ./server1.1
        ports:
            - "5031:5031"
        container_name: server1.1
        depends_on:
            - nginx
            - db
    server1.2:
        build:
            context: ./server1.2
        ports:
            - "5002:5002"
        container_name: server1.2
        depends_on:
            - nginx
            - db
    server1.3:
        build:
            context: ./server1.3
        ports:
            - "5003:5003"
        container_name: server1.3
        depends_on:
            - nginx
            - db
    server1.4:
        build:
            context: ./server1.4
        ports:
            - "5004:5004"
        container_name: server1.4
        depends_on:
            - nginx
            - db
    server1.5:
        build:
            context: ./server1.5
        ports:
            - "5005:5005"
        container_name: server1.5
        depends_on:
            - nginx
            - db
    server2.1:
        build:
            context: ./server2.1
        ports:
            - "5013:5013"
        container_name: server2.1
        depends_on:
            - nginx
            - db
    server2.3:
        build:
            context: ./server2.3
        ports:
            - "5015:5015"
        container_name: server2.3
        depends_on:
            - nginx
            - db
    server2.4:
        build:
            context: ./server2.4
        ports:
            - "5016:5016"
        container_name: server2.4
        depends_on:
            - nginx
            - db
    server2.6:
        build:
            context: ./server2.6
        ports:
            - "5018:5018"
        container_name: server2.6
        depends_on:
            - nginx
            - db
    server2.7:
        build:
            context: ./server2.7
        ports:
            - "5019:5019"
        container_name: server2.7
        depends_on:
            - nginx
            - db

    server2.8:
        build:
            context: ./server2.8
        ports:
            - "5020:5020"
        container_name: server2.8
        depends_on:
            - nginx
            - db

    server2.9:
        build:
            context: ./server2.9
        ports:
            - "5021:5021"
        container_name: server2.9
        depends_on:
            - nginx
            - db
    server2.10:
        build:
            context: ./server2.10
        ports:
            - "5022:5022"
        container_name: server2.10
        depends_on:
            - nginx
            - db
    server2.11:
        build:
            context: ./server2.11
        ports:
            - "5023:5023"
        container_name: server2.11
        depends_on:
            - nginx
            - db
    server2.12:
        build:
            context: ./server2.12
        ports:
            - "5024:5024"
        container_name: server2.12
        depends_on:
            - nginx
            - db
    server2.13:
        build:
            context: ./server2.13
        ports:
            - "5025:5025"
        container_name: server2.13
        depends_on:
            - nginx
            - db

    server2.14:
        build:
            context: ./server2.14
        ports:
            - "5026:5026"
        container_name: server2.14
        depends_on:
            - nginx
            - db
    server2.15:
        build:
            context: ./server2.15
        ports:
            - "5027:5027"
        container_name: server2.15
        depends_on:
            - nginx
            - db
    server2.16:
        build:
            context: ./server2.16
        ports:
            - "5028:5028"
        container_name: server2.16
        depends_on:
            - nginx
            - db
    
    
    server3.1:
        build:
            context: ./server3.1
        ports:
            - "5006:5006"
        container_name: server3.1
        depends_on:
            - nginx
            - db
    server3.2:
        build:
            context: ./server3.2
        ports:
            - "5007:5007"
        container_name: server3.2
        depends_on:
            - nginx
            - db

    server3.3:
        build:
            context: ./server3.3
        ports:
            - "5008:5008"
        container_name: server3.3
        depends_on:
            - nginx
            - db
    server3.4:
        build:
            context: ./server3.4
        ports:
            - "5009:5009"
        container_name: server3.4
        depends_on:
            - nginx
            - db
    server3.5:
        build:
            context: ./server3.5
        ports:
            - "5010:5010"
        container_name: server3.5
        depends_on:
            - nginx
            - db
    server3.6:
        build:
            context: ./server3.6
        ports:
            - "5011:5011"
        container_name: server3.6
        depends_on:
            - nginx
            - db

    server3.7:
        build:
            context: ./server3.7
        ports:
            - "5012:5012"
        container_name: server3.7
        depends_on:
            - nginx
            - db

    server3.8:
        build:
            context: ./server3.8
        ports:
            - "5030:5030"
        container_name: server3.8
        depends_on:
            - nginx
            - db
    


    db:
        image: postgres:14.1-alpine
        restart: always
        hostname: postgres
        environment:
        
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123
            - POSTGRES_DB=hoaccm
        ports:
            - "5029:5432"

        volumes: 
            - ./database.sql:/docker-entrypoint-initdb.d/database.sql


    nginx:
        restart: always
        image: nginx:latest
        container_name: nginx
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "8080:80"
        